name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Gandi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            # We need the whole repository to be able to update the other one
            fetch-depth: 0

      - name: Setup Gandi SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
            ssh-private-key: ${{ secrets.GS_SSH_KEY }}

      - name: Add Gandi SSH host to known hosts
        run: ssh-keyscan -H ${GANDI_HOST##*@} > ~/.ssh/known_hosts
        env:
          GANDI_HOST: ${{ secrets.GS_GANDI_SSH_HOST }}

      - name: Update Gandi repository
        run: |          
          git remote add gandi git+ssh://$GANDI_HOST/$GANDI_REPOSITORY
          git config --global user.email "amauy@carrade.eu"
          git config --global user.name "Amaury Carrade (from GitHub Actions)"
          git push --force gandi master
        env:
          GANDI_HOST: ${{ secrets.GS_GANDI_SSH_HOST }}
          GANDI_REPOSITORY: ${{ secrets.GS_GANDI_REPOSITORY }}

      - name: Deploy new version to Gandi Simple Hosting
        run: |
          ssh $GANDI_HOST "deploy $GANDI_REPOSITORY"
        env:
          GANDI_HOST: ${{ secrets.GS_GANDI_SSH_HOST }}
          GANDI_REPOSITORY: ${{ secrets.GS_GANDI_REPOSITORY }}
