name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Gandi
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gandi SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
            ssh-private-key: ${{ secrets.GS_SSH_KEY }}

      # Runs a set of commands using the runners shell
      - name: Update Gandi repository
        run: |
          git remote add gandi git+ssh://$GANDI_HOST/$GANDI_REPOSITORY
          git pull --rebase gandi master
          git push gandi master
        env:
          GANDI_HOST: ${{ secrets.GS_GANDI_SSH_HOST }}
          GANDI_REPOSITORY: ${{ secrets.GS_GANDI_REPOSITORY }}
      
      - name: Deploy new version to Gandi Simple Hosting
        run: |
          ssh $GANDI_HOST 'deploy $GANDI_REPOSITORY'
        env:
          GANDI_HOST: ${{ secrets.GS_GANDI_SSH_HOST }}
          GANDI_REPOSITORY: ${{ secrets.GS_GANDI_REPOSITORY }}
  
